apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "laa-assess-crime-forms.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      service: {{ include "laa-assess-crime-forms.fullname" . }}-metrics-svc
  endpoints:
  - port: metrics
    interval: 15s
