{{- if not (lookup "v1" "ConfigMap" {{ .Release.Namespace }} {{ include "laa-assess-crime-forms.fullname" . }}-settings) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laa-assess-crime-forms.fullname" . }}-settings
data:
  MAINTENANCE_MODE: 'false'
{{ end }}
