version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps


workflows:
  branch-build-approval:
    jobs:
      - build
