version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

references:
  _main-only: &main-only
      filters:
        branches:
          only: main
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps


workflows:
  build-deploy-main:
    jobs:
      - build
  
  build-deploy-branch: 
    filters:
      branches:
        ignore:
          - main
    jobs: 
      - build:
        <<: *main-only
