development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_HOST") { "redis://localhost:6379/1" } %>
  channel_prefix: laa_assess_non_standard_magistrate_fee_production
