feature_flags:
  dev_auth:
    local: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    development: true
    uat: true
    production: false # must never be enabled in the live service
  postal_evidence:
    local: <%= ENV.fetch("POSTAL_EVIDENCE", false) %>
    development: false
    uat: false
    production: false
  insights:
    local: <%= ENV.fetch("INSIGHTS", false) %>
    development: false
    uat: false
    production: false

