feature_flags:
  dev_auth:
    local: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    development: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    uat: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    production: false # must never be enabled in the live service

