# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  app: 1
  worker: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: "laa-assess-crime-forms-app"
fullnameOverride: "laa-assess-crime-forms-app"

service:
  type: ClusterIP
  port: 80
  internalPort: 3000
  workerPort: 7433

ingress:
  enabled: true
  namespace: laa-assess-crime-forms-dev
  className: modsec
  annotations:
      nginx.ingress.kubernetes.io/enable-modsecurity: "true"
      nginx.ingress.kubernetes.io/modsecurity-snippet: |
        SecRuleEngine On
        SecRequestBodyNoFilesLimit 524288
        SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
        SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6"
      external-dns.alpha.kubernetes.io/set-identifier: laa-assess-crime-forms-app-laa-assess-crime-forms-dev-green
      external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: dev.assess-crime-forms.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
          service:
            name: laa-assess-crime-forms-dev
            port:
              number: 3000

  tls:
    - hosts:
      - dev.assess-crime-forms.service.justice.gov.uk
      secretName: laa-assess-crime-forms-cert

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 500Mi

variables:
  environment: development
  appStoreUrl: https://main-nscc-store-dev.cloud-platform.service.justice.gov.uk
  enableSyncTriggerEndpoint: 'true'
  allowIndexing: 'false'

service_account:
  name: laa-assess-crime-forms-dev-irsa

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: [ "ALL" ]

# This is used to configure the temporary non-RDS postgres DB
postgresql:
  enabled: true
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  auth:
    database: nsm_assess_dev
    enablePostgresUser: true
    postgresPassword: postgres
  postgresqlUsername: postgres
  primary:
    persistence:
      enabled: true
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: [ "ALL" ]

# see https://artifacthub.io/packages/helm/bitnami/redis for parameters
redis:
  enabled: true
  architecture: standalone
  master:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: [ "ALL" ]
  auth:
    enabled: true
    password: redis

metabase:
  dashboardIds: 14
  siteUrl: 'https://uat.crime-forms-metabase.service.justice.gov.uk'

customErrorService:
  enabled: true
